name:                dsl-sixty-five-oh-two
version:             0.1.0.0
github:              "githubuser/dsl-sixty-five-oh-two"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A DSL for writing 65(C)02 bytecode. Please see the README on GitHub at <https://github.com/githubuser/dsl-sixty-five-oh-two#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- lens
- bytestring

library:
  source-dirs: src

executables:
  dsl-sixty-five-oh-two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsl-sixty-five-oh-two

tests:
  dsl-sixty-five-oh-two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsl-sixty-five-oh-two
