name:                dsl-sixty-five-oh-two
version:             0.1.0.0
github:              "aearnus/dsl-sixty-five-oh-two"
license:             MIT
author:              "Tyler Limkemann"
maintainer:          "tslimkemann42@gmail.com"
copyright:           "2018 Tyler Limkemann"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            An eDSL for writing 65(C)02 bytecode.
category:            DSL

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         An eDSL for writing 65(C)02 bytecode. Please see the README on GitHub at <https://github.com/aearnus/dsl-sixty-five-oh-two#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- containers
- lens
- bytestring

library:
  source-dirs: src

executables:
  dsl-sixty-five-oh-two-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsl-sixty-five-oh-two

tests:
  dsl-sixty-five-oh-two-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - dsl-sixty-five-oh-two
